# Log4j2 Configuration File
property.filename = logs
appenders = console, rollingFile

appender.console.type = Console
appender.console.name = stdout
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# Rolling File Appender - LOGFILE
appender.rollingFile.type = RollingFile
appender.rollingFile.name = LOGFILE
appender.rollingFile.fileName = ${filename}/movie-tracker.log
appender.rollingFile.filePattern = ${filename}/movie-tracker-%d{yyyy-MM-dd}-%i.log
appender.rollingFile.layout.type = PatternLayout
appender.rollingFile.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

# File Rolling Policies
appender.rollingFile.policies.type = Policies
appender.rollingFile.policies.size.type = SizeBasedTriggeringPolicy
appender.rollingFile.policies.size.size = 2MB

# Keep a maximum of 5 backup files
appender.rollingFile.strategy.type = DefaultRolloverStrategy
appender.rollingFile.strategy.max = 5

loggers=file
logger.file.name=com.aozelce
logger.file.level = debug
logger.file.additivity = false
logger.file.appenderRefs = rollingFile, stdout
logger.file.appenderRef.file.ref = LOGFILE
logger.file.appenderRef.stdout.ref = stdout

rootLogger.level = debug
rootLogger.appenderRefs = stdout, rollingFile
rootLogger.appenderRef.stdout.ref = stdout
rootLogger.appenderRef.file.ref = LOGFILE